[package]
name = "revolt"
version = "0.1.0"
authors = ["KiraCoding"]
edition = "2021"
rust-version = "1.64.0"
description = "Webview based Discord client"
license = "Apache-2.0 OR MIT"

[dependencies]
directories = { version = "5.0.1" }
open = { version = "5.0.0" }
wry = { version = "0.31.1", default-features = false }

[profile.release]
codegen-units = 1
strip = true
lto = true
