[package]
name = "volt"
version = "0.1.0"
authors = ["KiraCoding"]
edition = "2021"
rust-version = "1.64.0"
description = "Webview based Discord client"
license = "GPL-3.0-only"

[dependencies]
anyhow = { version = "1.0.80" }
directories = { version = "5.0.1" }
open = { version = "5.0.2" }
tao = { version = "0.26.1" }
wry = { version = "0.37.0" }

[build-dependencies]
swc = { version = "0.273.13" }
swc_common = { version = "0.33.18" }
winres = { version = "0.1.12" }

[profile.release]
codegen-units = 1
strip = true
lto = true
