[advisories]
version = 2
yanked = "warn"

[bans]
multiple-versions = "allow"

[licenses]
version = 2
allow = [
    "Apache-2.0 WITH LLVM-exception",
    "Apache-2.0",
    "BSD-3-Clause",
    "GPL-3.0",
    "MIT",
    "MPL-2.0",
    "Unicode-DFS-2016",
]

[sources]
unknown-registry = "deny"
unknown-git = "deny"
